version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "50051:50051"
      - "8080:8080"
    environment:
      REDIS_ADDR: redis:6379
      REDIS_DB: 0
      GRPC_ADDR: ":50051"
      HTTP_ADDR: ":8080"
      ADMIN_TOKEN: "${ADMIN_TOKEN:-supersecrettoken}"
      LOG_LEVEL: info
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis-data: